### ISSUE TITLE
Dell EMC S5248: Fanout and fanin required for all interface

### ISSUE THREAD

**Issue by waliulislam** [open-switch/opx-platform-config#72]
Currently We can fanout 100 gig interface to 1x1 40gig , 4x1 25gig and 4x1 10gig. But after fan out we fail to do Fan in to 1x1 100gig.
```
root@OPX:~# opx-config-fanout e101-053-0 4x1 10g  
dell-pg/port-groups-state/port-group-state/id = port-group-15
dell-pg/port-groups/port-group/id = port-group-15
current_mode 4
current_speed 7
Deleting.. e101-053-0
Completed...
Creating interface e101-053-1
Creating interface e101-053-2
Creating interface e101-053-3
Creating interface e101-053-4
Successfully created interfaces...
root@OPX:~# opx-config-fanout e101-053-1 1x1 100g
dell-pg/port-groups-state/port-group-state/id = port-group-15
dell-pg/port-groups/port-group/id = port-group-15
current_mode 4
current_speed 7
Port already configured as breakout mode 4 and speed 7
root@OPX:~# 
```
Also we need to fanout 25gig interface to 1x1 10g, to support 10gig transceiver.

```
root@OPX:~# opx-config-fanout e101-017-0 1x1 10g
Invalid break mode and port speed combination
root@OPX:~
```

**Comment by Tejaswi-Goel** [comment]
mode = 4 = 1x1
speed = 7 = 100g
fanin failed because each interface belongs to a port-group on s52xx platforms, and temporary workaround of doing fannout did not change the port group breakout mode and speed. So, we need to a develop a utility to fanout the port-group instead of an individual interface and change the port-group configuration accordingly.

**Comment by waliulislam** [comment]
3.1.0-rc0 provide a new opx-config-fanout to address the issue
